# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                             _      _____   ___  _  _______  _______                          | #
# |                            | | /| / / _ | / _ \/ |/ /  _/ |/ / ___/                          | #
# |                            | |/ |/ / __ |/ , _/    // //    / (_ /                           | #
# |                            |__/|__/_/ |_/_/|_/_/|_/___/_/|_/\___/                            | #
# |                                                                                              | #
# |                                                                                              | #
# |                                                                                              | #
# |  DISCORD:     ox#7625                                                                        | #
# |  BUG REPORTS: https://discord.gg/PE2VM2YMCz                                                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #


# +----------------------------------------------------------------------------------------------+ #
# |
# |                                      PERMISSION SETTINGS
# |
# |                               경고 추가, 차감에대한 권한을 설정합니다.
# |
# +----------------------------------------------------------------------------------------------+ #
permission: test.test


# +----------------------------------------------------------------------------------------------+ #
# |
# |                                         DATA SETTINGS
# |
# |                          DB 또는 Config 중에 하나로 저장장치를 선택합니다.
# |                        example ==> saveData: Config [## 대,소문자 구별 ##]
# |
# +----------------------------------------------------------------------------------------------+ #
saveData: DB


# +----------------------------------------------------------------------------------------------+ #
# |
# |                                       DATABASE SETTINGS
# |
# |               [ 저장창치로 DB를 선택했다면 ] 경고에대한 모든 기록을 데이터베이스에 저장합니다.
# |
# +----------------------------------------------------------------------------------------------+ #
mysql:
  address: localhost
  port: 3306
  user: root
  password: 1234
  dbName: paperserver


# +----------------------------------------------------------------------------------------------+ #
# |
# |                                        WARNING SETTINGS
# |
# |                     경고에대한 카운트를하고 해당 횟수에 도달하면 일정 시간 밴을합니다.
# |
# +----------------------------------------------------------------------------------------------+ #
ban1:
  count: 3
  day: 1
  hour: 0
  min: 0
  sec: 0

ban2:
  count: 5
  day: 2
  hour: 0
  min: 0
  sec: 0

ban3:
  count: 7
  day: 3
  hour: 0
  min: 0
  sec: 0

ban4:
  count: 10
  day: 4
  hour: 0
  min: 0
  sec: 0
